#!/bin/bash

SINK=$( pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1 )
NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
MUTED=$( pactl list sinks | grep '^[[:space:]]Mute:' | head -n$(( $SINK + 1 )) | tail -n 1 | awk '{ print $2 }' )

if [[ "$MUTED" = "yes" ]];
then
	echo muted
else
      	echo $NOW\%
fi
