(deftheme zenburn
  "The Zenburn color theme")

(custom-theme-set-faces
 'zenburn
 '(button ((t (:underline t))))
 '(link ((t (:weight bold :underline t :foreground "#F0DFAF"))))
 '(link-visited ((t (:weight normal :underline t :foreground "#D0BF8F"))))
 '(default ((t (:family "default" :foundry "default" :width normal :height 1 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#DCDCCC" :background "#3F3F3F" :stipple nil))))
 '(cursor ((t (:foreground "#DCDCCC" :background "#FFFFEF"))))
 '(escape-glyph ((t (:weight bold :foreground "#F0DFAF"))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#F0DFAF" :background "#2B2B2B"))))
 '(highlight ((t (:background "#383838"))))
 '(completions-annotations ((t (:foreground "#656555"))))
 '(match ((t (:weight bold :foreground "#DFAF8F" :background "#2B2B2B"))))
 '(isearch ((t (:weight bold :foreground "#D0BF8F" :background "#5F5F5F"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:weight bold :foreground "#D0BF8F" :background "#383838"))))
 '(menu ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width -1 :color nil :style released-button) :foreground "#8FB28F" :background "#2B2B2B"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#F0DFAF"))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#5F7F5F" :background "#383838"))))
 '(region ((((class color) (min-colors 89)) (:background "#2B2B2B"))))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#DCDCCC"))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#F0DFAF"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#F0DFAF"))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#F0DFAF"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#7F9F7F"))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#D0BF8F"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#383838"))))
 '(linum ((t (:foreground "#9FC59F" :background "#3F3F3F"))))
 '(org-agenda-date-today ((t (:weight bold :slant italic :foreground "#FFFFEF")))))

(provide-theme 'zenburn)
